### ISSUE TITLE
Detail Page cannot survive after browser refresh

### ISSUE THREAD

**Issue by zerg000000** [alysachan830/user-list#1]

**Comment by alysachan830** [comment]
Thank you for the comment. Here are the changes I made:

- Store person's detail in sessionStorage. When the page is reloaded, show the data from sessionStorage. If the data is not found in sessionStorage, call API and show the data that matches the user id in URL. If there is no match, redirect user to homepage. 

- Move the function that calls API and fetches data into a mixin, because it will be reused in both homepage and person detail page. 

Outcome URL:
[User List](https://user-list-kappa.vercel.app/)
